server:
  port: 9091
   
spring:
  jpa:
    properties:
     hibernate:
      dialet: org.hibernate.dialect.MySQL5Dialect
    hibernate:
     ddl-auto: update
     naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
       
  datasource: 
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ns_asset_mgt?autoReconnect=true&useSSL=false
    username: root
    password: 