server:
  port: 9091
   
spring:
  jpa:
    properties:
     hibernate:
      dialet: org.hibernate.dialect.MySQL5Dialect
    hibernate:
     ddl-auto: update
     naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
       
  datasource: 
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ns_asset_mgt
    username: sa
    password: 